### ISSUE TITLE
How to copy raw text corpora to repo's?

### ISSUE THREAD

**Issue by slavikkom** [mt2017-tartu-shared-task/nmt-system-C#1]
Should it be downloaded here, at github? Data files too large for download.  How can we deal with it?

**Comment by MaksymDel** [comment]
First, clone this remote repo to your local HPC folder. See the last section of [git-github.pdf](https://github.com/mt2017-tartu-shared-task/materials/blob/master/git-github.pdf) for details. 

Second, copy the raw data from my HPC data folder, to your new repo data folder (which is now also on HPC). See the last section of [lab1.pdf](https://github.com/mt2017-tartu-shared-task/materials/blob/master/lab1.pdf) for exact copy command and other details.

Lastly, corpora (and models) should not be pushed to github in any way. That is why, /data and /model folders contain .gitignore files that will prevent you from doing this. 

Again, you should start with cloning this repo: 
`git clone https://github.com/mt2017-tartu-shared-task/nmt-system-C`.

**Comment by slavikkom** [comment]
Thanks. I enter my local HPC folder (komisare), create new folder "project", enter this new folder, clone repository from github, enter to data folder, copy neccessary data. Is it right? Can I now perform operations from lab1.pdf? Can my team partner work from this folder, or it is should be some shared folder on HPC?

**Comment by MaksymDel** [comment]
It is right. 

Your teammate should have her own copy of the code repo. 

You then can synchronize data and models via copy command (e.g. ask her to copy prepared data to her _data_ folder; or copy trained model to your _model_ folder if it is she who trained the model).  

Code can be synchronized via git/github.
