### ISSUE TITLE
Problem with understanding SLURM

### ISSUE THREAD

**Issue by slavikkom** [mt2017-tartu-shared-task/nmt-system-C#2]
After making copy of text corpora, I run all commands in lab1.pdf before paragraph "Training NMT model with OpenNMT-py" with two differences: splitting corpus into test, dev, train with values (1-1000000, 1000001-150000, 19500000 instead of 1-100, 101-200, 200-9000) and argument in first learn BPE 50000 instead of 10000. Is it right or I should rerun with some other parameters? If all right, for training model I need to use SLURM. After reading materials I didn't get into what to do, how to use SLURM manager to run commands from lab1.pdf (or it should be some other commans). Thanks in advance.

**Comment by MaksymDel** [comment]
You are on the right track, keep going!

Regarding split sizes (from lab1.pdf): 
![image](https://user-images.githubusercontent.com/8141935/30671348-19525638-9e6f-11e7-85fd-765977e9c047.png)
So I suggest making it 50.000 for test, and 25.000 for dev, just as specified.

Regarding BPE vocabulary size:
![image](https://user-images.githubusercontent.com/8141935/30671502-f4d85e3c-9e6f-11e7-8bf2-d82ccda2cdbd.png)
I think 50000 is ok; however, with 30000 your model will train faster. 

Regarding SLURM:
- SLURM is just another way to run the commands from lab1
- We prepared a helper script ([link](https://github.com/mt2017-tartu-shared-task/materials/blob/master/rocket-sbatch-sample.sh)), where all you need is to insert your command at the end
- Consult this tutorial to understand the script and slurm better ([link](https://www.hpc.ut.ee/slurm))
- Try running this helper script with your commands on small data first to master it

**Comment by slavikkom** [comment]
We need to copy helper script to local HPC, modify it and then execute? Which commands should be added: all commands below paragraph "7. Build vocabulary" (with path change, where neccessary), or some commands should be omitted (e.g. commands from paragraph 8 "Train model" where train.py script needs gpuid as parameter)? Thanks in advance.

**Comment by MaksymDel** [comment]
> We need to copy helper script to local HPC, modify it and then execute?

Yes

I do not suggest running all the command at once. Better run one command per file. 

As for _gpuid_ parameter, do not be scared to figure out it yourself (on small data). Try to run your .sh script without it, then with it. Use _nvidia-smi_ and _top_ commands to check how your process is running.

**Comment by slavikkom** [comment]
From which directory should I run command nvidia-smi? When run this command, I got message "command not found".

**Comment by MaksymDel** [comment]
You should ssh to some gpu server (i.e. falcon2 or falcon1) and run it from there

**Comment by slavikkom** [comment]
I created 3 scripts; build_vocabulary, train_model, translate. Is there any other commands that should be run via scripts (e.g. evaluate)? For first 9000 tokens from big dataset I received 2.73 BLEU. For running on big data, I should run three scripts one by one, or should create one script with three commans (build vocabulary, train and translate)?

**Comment by MaksymDel** [comment]
> Is there any other commands that should be run via scripts (e.g. evaluate)? 

I believe you can safely run 'evaluate' on test set directly since it does not take much memory and runs almost instantly, so no other commands should be run.

>  For first 9000 tokens from big dataset I received 2.73 BLEU

2.73 BLEU is too low. For how many epochs did you train your toy model? Try letting it stop training automatically, maybe it will help you to get a bit more BLEU on this toy data.

> I should run three scripts one by one, or should create one script with three commans (build vocabulary, train and translate)?

I suggest running one by one.

**Comment by slavikkom** [comment]
Running stops automatically after 13th epochs. Final model that I recieved was demo-model_acc_24.96_ppl_157.53_e13.pt

**Comment by MaksymDel** [comment]
The model looks ok for me, so if you have not made any mistakes during reproducing lab1, you should be fine. 

Such a low BLEU might be due to unlucky data shuffling, but it almost does not matter when you train on big data.

**Comment by slavikkom** [comment]
Can I safely close PowerShell while running training on big data?

**Comment by MaksymDel** [comment]
The behaviour does not change between toy data and big data, so feel free to check it yourself on small data.  E.g. run something like this in your SLURM script:
`uname -a`
`sleep 60`
`pwd`
Then see a content of your output file. It should contain your username at the last line.

After that quickly close powershell. Then shh again after a minute, and If it does not kill a process, you will have your current directory written to the end of the output file.

Getting things done while mastering supplementing tools is a usual part of ML researcher workflow, so we want you to feel comfortable experimenting with new tools & frameworks.

**Comment by slavikkom** [comment]
It seems to me that after my computer get overloaded at night, it kills training process. Can it be possible? After running nvidia-smi I found no running processes, no new models appear at /models folder.

**Comment by MaksymDel** [comment]
Are you sure you run your .sh script with `sbatch` command?

**Comment by slavikkom** [comment]
Thanks. After your advice, I run script (located in OpenNMT-py folder, running from falcon2 OpenNMT folder) with sbatch command, script was copy of template + line: python train.py -data /gpfs/hpchome/komisare/project/data/raw-all/rdy -config train.cfg -save_model /gpfs/hpchome/komisare/project/models/demo-model -gpuid 1 (all paths are correct). I recieved jobid. After couple of time, I decide to check progress with squeue, sstat and similar commands, but for this jobid output was negative (no such job id in queue, wrong job id specified etc).

**Comment by slavikkom** [comment]
After consulting with classmates and clearly reading materials, I found solution.
