### ISSUE TITLE
Queue in SLURM

### ISSUE THREAD

**Issue by slavikkom** [mt2017-tartu-shared-task/nmt-system-C#6]
Can it be that jobs submitted several days ago are still in queue? Maybe, all nodes are busy or something like that? Is there any way to deal with it?

**Comment by MaksymDel** [comment]
Nodes are not busy, you should be able to run a gpu job via slurm. Try to decrease resources and resubmit, or if it does not help, ask here: support@hpc.ut.ee. Probably, include also your squeue command output in the email.
